<?php
// globals.php

// Definir una variable global con los países
$countries = [
    ["name" => "Afghanistan", "code" => "af"],
    ["name" => "Åland Islands", "code" => "ax"],
    ["name" => "Albania", "code" => "al"],
    ["name" => "Algeria", "code" => "dz"],
    ["name" => "American Samoa", "code" => "as"],
    ["name" => "Andorra", "code" => "ad"],
    ["name" => "Angola", "code" => "ao"],
    ["name" => "Anguilla", "code" => "ai"],
    ["name" => "Antarctica", "code" => "aq"],
    ["name" => "Antigua and Barbuda", "code" => "ag"],
    ["name" => "Argentina", "code" => "ar"],
    ["name" => "Armenia", "code" => "am"],
    ["name" => "Aruba", "code" => "aw"],
    ["name" => "Australia", "code" => "au"],
    ["name" => "Austria", "code" => "at"],
    ["name" => "Azerbaijan", "code" => "az"],
    ["name" => "Bahamas", "code" => "bs"],
    ["name" => "Bahrain", "code" => "bh"],
    ["name" => "Bangladesh", "code" => "bd"],
    ["name" => "Barbados", "code" => "bb"],
    ["name" => "Belarus", "code" => "by"],
    ["name" => "Belgium", "code" => "be"],
    ["name" => "Belize", "code" => "bz"],
    ["name" => "Benin", "code" => "bj"],
    ["name" => "Bermuda", "code" => "bm"],
    ["name" => "Bhutan", "code" => "bt"],
    ["name" => "Bolivia, Plurinational State of", "code" => "bo"],
    ["name" => "Bonaire, Sint Eustatius and Saba", "code" => "bq"],
    ["name" => "Bosnia and Herzegovina", "code" => "ba"],
    ["name" => "Botswana", "code" => "bw"],
    ["name" => "Bouvet Island", "code" => "bv"],
    ["name" => "Brazil", "code" => "br"],
    ["name" => "British Indian Ocean Territory", "code" => "io"],
    ["name" => "Brunei Darussalam", "code" => "bn"],
    ["name" => "Bulgaria", "code" => "bg"],
    ["name" => "Burkina Faso", "code" => "bf"],
    ["name" => "Burundi", "code" => "bi"],
    ["name" => "Cambodia", "code" => "kh"],
    ["name" => "Cameroon", "code" => "cm"],
    ["name" => "Canada", "code" => "ca"],
    ["name" => "Cape Verde", "code" => "cv"],
    ["name" => "Cayman Islands", "code" => "ky"],
    ["name" => "Central African Republic", "code" => "cf"],
    ["name" => "Chad", "code" => "td"],
    ["name" => "Chile", "code" => "cl"],
    ["name" => "China", "code" => "cn"],
    ["name" => "Christmas Island", "code" => "cx"],
    ["name" => "Cocos (Keeling) Islands", "code" => "cc"],
    ["name" => "Colombia", "code" => "co"],
    ["name" => "Comoros", "code" => "km"],
    ["name" => "Congo", "code" => "cg"],
    ["name" => "Congo, The Democratic Republic of the", "code" => "cd"],
    ["name" => "Cook Islands", "code" => "ck"],
    ["name" => "Costa Rica", "code" => "cr"],
    ["name" => "Croatia", "code" => "hr"],
    ["name" => "Cuba", "code" => "cu"],
    ["name" => "Curaçao", "code" => "cw"],
    ["name" => "Cyprus", "code" => "cy"],
    ["name" => "Czech Republic", "code" => "cz"],
    ["name" => "Denmark", "code" => "dk"],
    ["name" => "Djibouti", "code" => "dj"],
    ["name" => "Dominica", "code" => "dm"],
    ["name" => "Dominican Republic", "code" => "do"],
    ["name" => "Ecuador", "code" => "ec"],
    ["name" => "Egypt", "code" => "eg"],
    ["name" => "El Salvador", "code" => "sv"],
    ["name" => "Equatorial Guinea", "code" => "gq"],
    ["name" => "Eritrea", "code" => "er"],
    ["name" => "Estonia", "code" => "ee"],
    ["name" => "Ethiopia", "code" => "et"],
    ["name" => "Falkland Islands (Malvinas)", "code" => "fk"],
    ["name" => "Faroe Islands", "code" => "fo"],
    ["name" => "Fiji", "code" => "fj"],
    ["name" => "Finland", "code" => "fi"],
    ["name" => "France", "code" => "fr"],
    ["name" => "French Guiana", "code" => "gf"],
    ["name" => "French Polynesia", "code" => "pf"],
    ["name" => "French Southern Territories", "code" => "tf"],
    ["name" => "Gabon", "code" => "ga"],
    ["name" => "Gambia", "code" => "gm"],
    ["name" => "Georgia", "code" => "ge"],
    ["name" => "Germany", "code" => "de"],
    ["name" => "Ghana", "code" => "gh"],
    ["name" => "Gibraltar", "code" => "gi"],
    ["name" => "Greece", "code" => "gr"],
    ["name" => "Greenland", "code" => "gl"],
    ["name" => "Grenada", "code" => "gd"],
    ["name" => "Guadeloupe", "code" => "gp"],
    ["name" => "Guam", "code" => "gu"],
    ["name" => "Guatemala", "code" => "gt"],
    ["name" => "Guernsey", "code" => "gg"],
    ["name" => "Guinea", "code" => "gn"],
    ["name" => "Guinea-Bissau", "code" => "gw"],
    ["name" => "Guyana", "code" => "gy"],
    ["name" => "Haiti", "code" => "ht"],
    ["name" => "Heard Island and McDonald Islands", "code" => "hm"],
    ["name" => "Holy See (Vatican City State)", "code" => "va"],
    ["name" => "Honduras", "code" => "hn"],
    ["name" => "Hong Kong", "code" => "hk"],
    ["name" => "Hungary", "code" => "hu"],
    ["name" => "Iceland", "code" => "is"],
    ["name" => "India", "code" => "in"],
    ["name" => "Indonesia", "code" => "id"],
    ["name" => "Iran", "code" => "ir"],
    ["name" => "Iraq", "code" => "iq"],
    ["name" => "Ireland", "code" => "ie"],
    ["name" => "Isle of Man", "code" => "im"],
    ["name" => "Israel", "code" => "il"],
    ["name" => "Italy", "code" => "it"],
    ["name" => "Ivory Coast", "code" => "ci"],
    ["name" => "Jamaica", "code" => "jm"],
    ["name" => "Japan", "code" => "jp"],
    ["name" => "Jersey", "code" => "je"],
    ["name" => "Jordan", "code" => "jo"],
    ["name" => "Kazakhstan", "code" => "kz"],
    ["name" => "Kenya", "code" => "ke"],
    ["name" => "Kiribati", "code" => "ki"],
    ["name" => "Korea, Democratic Peoples Republic of", "code" => "kp"],
    ["name" => "Korea, Republic of", "code" => "kr"],
    ["name" => "Kuwait", "code" => "kw"],
    ["name" => "Kyrgyzstan", "code" => "kg"],
    ["name" => "Lao Peoples Democratic Republic", "code" => "la"],
    ["name" => "Latvia", "code" => "lv"],
    ["name" => "Lebanon", "code" => "lb"],
    ["name" => "Lesotho", "code" => "ls"],
    ["name" => "Liberia", "code" => "lr"],
    ["name" => "Libya", "code" => "ly"],
    ["name" => "Liechtenstein", "code" => "li"],
    ["name" => "Lithuania", "code" => "lt"],
    ["name" => "Luxembourg", "code" => "lu"],
    ["name" => "Macao", "code" => "mo"],
    ["name" => "Macedonia", "code" => "mk"],
    ["name" => "Madagascar", "code" => "mg"],
    ["name" => "Malawi", "code" => "mw"],
    ["name" => "Malaysia", "code" => "my"],
    ["name" => "Maldives", "code" => "mv"],
    ["name" => "Mali", "code" => "ml"],
    ["name" => "Malta", "code" => "mt"],
    ["name" => "Marshall Islands", "code" => "mh"],
    ["name" => "Martinique", "code" => "mq"],
    ["name" => "Mauritania", "code" => "mr"],
    ["name" => "Mauritius", "code" => "mu"],
    ["name" => "Mayotte", "code" => "yt"],
    ["name" => "Mexico", "code" => "mx"],
    ["name" => "Micronesia, Federated States of", "code" => "fm"],
    ["name" => "Moldova, Republic of", "code" => "md"],
    ["name" => "Monaco", "code" => "mc"],
    ["name" => "Mongolia", "code" => "mn"],
    ["name" => "Montenegro", "code" => "me"],
    ["name" => "Montserrat", "code" => "ms"],
    ["name" => "Morocco", "code" => "ma"],
    ["name" => "Mozambique", "code" => "mz"],
    ["name" => "Myanmar", "code" => "mm"],
    ["name" => "Namibia", "code" => "na"],
    ["name" => "Nauru", "code" => "nr"],
    ["name" => "Nepal", "code" => "np"],
    ["name" => "Netherlands", "code" => "nl"],
    ["name" => "New Caledonia", "code" => "nc"],
    ["name" => "New Zealand", "code" => "nz"],
    ["name" => "Nicaragua", "code" => "ni"],
    ["name" => "Niger", "code" => "ne"],
    ["name" => "Nigeria", "code" => "ng"],
    ["name" => "Niue", "code" => "nu"],
    ["name" => "Norfolk Island", "code" => "nf"],
    ["name" => "Northern Mariana Islands", "code" => "mp"],
    ["name" => "Norway", "code" => "no"],
    ["name" => "Oman", "code" => "om"],
    ["name" => "Pakistan", "code" => "pk"],
    ["name" => "Palau", "code" => "pw"],
    ["name" => "Palestinian Territory, Occupied", "code" => "ps"],
    ["name" => "Panama", "code" => "pa"],
    ["name" => "Papua New Guinea", "code" => "pg"],
    ["name" => "Paraguay", "code" => "py"],
    ["name" => "Peru", "code" => "pe"],
    ["name" => "Philippines", "code" => "ph"],
    ["name" => "Pitcairn", "code" => "pn"],
    ["name" => "Poland", "code" => "pl"],
    ["name" => "Portugal", "code" => "pt"],
    ["name" => "Puerto Rico", "code" => "pr"],
    ["name" => "Qatar", "code" => "qa"],
    ["name" => "Réunion", "code" => "re"],
    ["name" => "Romania", "code" => "ro"],
    ["name" => "Russian Federation", "code" => "ru"],
    ["name" => "Rwanda", "code" => "rw"],
    ["name" => "Saint Barthélemy", "code" => "bl"],
    ["name" => "Saint Helena, Ascension and Tristan da Cunha", "code" => "sh"],
    ["name" => "Saint Kitts and Nevis", "code" => "kn"],
    ["name" => "Saint Lucia", "code" => "lc"],
    ["name" => "Saint Martin (French part)", "code" => "mf"],
    ["name" => "Saint Pierre and Miquelon", "code" => "pm"],
    ["name" => "Saint Vincent and the Grenadines", "code" => "vc"],
    ["name" => "Samoa", "code" => "ws"],
    ["name" => "San Marino", "code" => "sm"],
    ["name" => "Sao Tome and Principe", "code" => "st"],
    ["name" => "Saudi Arabia", "code" => "sa"],
    ["name" => "Senegal", "code" => "sn"],
    ["name" => "Serbia", "code" => "rs"],
    ["name" => "Seychelles", "code" => "sc"],
    ["name" => "Sierra Leone", "code" => "sl"],
    ["name" => "Singapore", "code" => "sg"],
    ["name" => "Sint Maarten (Dutch part)", "code" => "sx"],
    ["name" => "Slovakia", "code" => "sk"],
    ["name" => "Slovenia", "code" => "si"],
    ["name" => "Solomon Islands", "code" => "sb"],
    ["name" => "Somalia", "code" => "so"],
    ["name" => "South Africa", "code" => "za"],
    ["name" => "South Georgia and the South Sandwich Islands", "code" => "gs"],
    ["name" => "South Sudan", "code" => "ss"],
    ["name" => "Spain", "code" => "es"],
    ["name" => "Sri Lanka", "code" => "lk"],
    ["name" => "Sudan", "code" => "sd"],
    ["name" => "Suriname", "code" => "sr"],
    ["name" => "Svalbard and Jan Mayen", "code" => "sj"],
    ["name" => "Swaziland", "code" => "sz"],
    ["name" => "Sweden", "code" => "se"],
    ["name" => "Switzerland", "code" => "ch"],
    ["name" => "Syria", "code" => "sy"],
    ["name" => "Taiwan", "code" => "tw"],
    ["name" => "Tajikistan", "code" => "tj"],
    ["name" => "Tanzania", "code" => "tz"],
    ["name" => "Thailand", "code" => "th"],
    ["name" => "Timor-Leste", "code" => "tl"],
    ["name" => "Togo", "code" => "tg"],
    ["name" => "Tokelau", "code" => "tk"],
    ["name" => "Tonga", "code" => "to"],
    ["name" => "Trinidad and Tobago", "code" => "tt"],
    ["name" => "Tunisia", "code" => "tn"],
    ["name" => "Turkey", "code" => "tr"],
    ["name" => "Turkmenistan", "code" => "tm"],
    ["name" => "Turks and Caicos Islands", "code" => "tc"],
    ["name" => "Tuvalu", "code" => "tv"],
    ["name" => "Uganda", "code" => "ug"],
    ["name" => "Ukraine", "code" => "ua"],
    ["name" => "United Arab Emirates", "code" => "ae"],
    ["name" => "United Kingdom", "code" => "gb"],
    ["name" => "United States", "code" => "us"],
    ["name" => "United States Minor Outlying Islands", "code" => "um"],
    ["name" => "Uruguay", "code" => "uy"],
    ["name" => "Uzbekistan", "code" => "uz"],
    ["name" => "Vanuatu", "code" => "vu"],
    ["name" => "Venezuela, Bolivarian Republic of", "code" => "ve"],
    ["name" => "Vietnam", "code" => "vn"],
    ["name" => "Virgin Islands, British", "code" => "vg"],
    ["name" => "Virgin Islands, U.S.", "code" => "vi"],
    ["name" => "Wallis and Futuna", "code" => "wf"],
    ["name" => "Western Sahara", "code" => "eh"],
    ["name" => "Yemen", "code" => "ye"],
    ["name" => "Zambia", "code" => "zm"],
    ["name" => "Zimbabwe", "code" => "zw"],
];


$fecha = [
    "today"     => "Hoy",
    "yesterday" => "Ayer",
    "3d"        => "Últimos 3 días",
    "7d"        => "Última semana",
    "1m"        => "Último mes",
];


$categoria_list = [
    ["name" => "Gestión Nacional",        "title" => "Gestión Nacional"],
    ["name" => "Gestión Regional",        "title" => "Gestión Regional"],
    ["name" => "Gestión Municipal",       "title" => "Gestión Municipal"],
    ["name" => "Voluntariado",             "title" => "Voluntariado"],
    ["name" => "Prácticas Profesionales", "title" => "Prácticas Profesionales"],
    ["name" => "Prácticas Pre Profesionales", "title" => "Prácticas Pre Profesionales"],
    ["name" => "Educación",                "title" => "Educación"],
    ["name" => "Consultoría",              "title" => "Consultoría"],
    ["name" => "Agencias de Viajes",       "title" => "Agencias de Viajes"],
    ["name" => "Restaurantes",             "title" => "Restaurantes"],
    ["name" => "Hotelería",                "title" => "Hotelería"],
];


$modality_list = [
    ["name" => "Mixta",      "title" => "Mixta"],
    ["name" => "Presencial", "title" => "Presencial"],
    ["name" => "Remoto",     "title" => "Remoto"],
];

$type_day_list = [
    ["name" => "Jornada Nocturna",         "title" => "Jornada Nocturna"],
    ["name" => "Jornada por Suplencia",    "title" => "Jornada por Suplencia"],
    ["name" => "Jornada por Horas",        "title" => "Jornada por Horas"],
    ["name" => "Jornada Tiempo Parcial",   "title" => "Jornada Tiempo Parcial"],
    ["name" => "Jornada Completa",         "title" => "Jornada Completa"],
];

$type_contract_list = [
    ["name" => "Teletrabajo",              "title" => "Teletrabajo"],
    ["name" => "Parcial - Medio Tiempo",   "title" => "Parcial - Medio Tiempo"],
    ["name" => "Para obra o servicio",     "title" => "Para obra o servicio"],
    ["name" => "Temporal",                  "title" => "Temporal"],
    ["name" => "Determinado a plazo fijo", "title" => "Determinado a plazo fijo"],
    ["name" => "Indefinido",                "title" => "Indefinido"],
];

$range_salary = [
    "l750"   => "Menos de S/750",
    "m750"   => "Más de S/750",
    "m1500"  => "Más de S/1,500",
    "m3000"  => "Más de S/3,000",
    "m6000"  => "Más de S/6,000",
    "m10000" => "Más de S/10,000",
];


$GLOBALS['countries'] = $countries;
$GLOBALS['fecha'] = $fecha;
$GLOBALS['categoria_list'] = $categoria_list;
$GLOBALS['modality_list'] = $modality_list;
$GLOBALS['type_day_list'] = $type_day_list;
$GLOBALS['type_contract_list'] = $type_contract_list;
$GLOBALS['range_salary'] = $range_salary;

$specialty_list = [
    ["name" => "Economía y Negocios Internacionales", "title" => "Economía y Negocios Internacionales"],
    ["name" => "Negocios Internacionales", "title" => "Negocios Internacionales"],
    ["name" => "Arte", "title" => "Arte"],
    ["name" => "Otro", "title" => "Otro"],
    ["name" => "Estadística", "title" => "Estadística"],
    ["name" => "Ingeniería Sanitaria", "title" => "Ingeniería Sanitaria"],
    ["name" => "Ingeniería de Sistemas", "title" => "Ingeniería de Sistemas"],
    ["name" => "Ingeniería Civil", "title" => "Ingeniería Civil"],
    ["name" => "Ingeniería Ambiental", "title" => "Ingeniería Ambiental"],
    ["name" => "Aviación Comercial", "title" => "Aviación Comercial"],
    ["name" => "Diseño Grafico", "title" => "Diseño Grafico"],
    ["name" => "Secretariado", "title" => "Secretariado"],
    ["name" => "Computación e Informática", "title" => "Computación e Informática"],
    ["name" => "Arquitectura y Urbanismo", "title" => "Arquitectura y Urbanismo"],
    ["name" => "Arquitectura", "title" => "Arquitectura"],
    ["name" => "Arqueología", "title" => "Arqueología"],
    ["name" => "Historía", "title" => "Historía"],
    ["name" => "Trabajo Social", "title" => "Trabajo Social"],
    ["name" => "Antropología", "title" => "Antropología"],
    ["name" => "Geografía", "title" => "Geografía"],
    ["name" => "Sociología", "title" => "Sociología"],
    ["name" => "Marketing", "title" => "Marketing"],
    ["name" => "Ciencias de la Comunicación", "title" => "Ciencias de la Comunicación"],
    ["name" => "Psicología", "title" => "Psicología"],
    ["name" => "Economía", "title" => "Economía"],
    ["name" => "Medicina Humana", "title" => "Medicina Humana"],
    ["name" => "Biología", "title" => "Biología"],
    ["name" => "Enfermería", "title" => "Enfermería"],
    ["name" => "Derecho", "title" => "Derecho"],
    ["name" => "Administración", "title" => "Administración"],
    ["name" => "Ciencias Contables y Financieras", "title" => "Ciencias Contables y Financieras"],
    ["name" => "Ingeniería", "title" => "Ingeniería"],
    ["name" => "Educación", "title" => "Educación"],
    ["name" => "Gastronomía", "title" => "Gastronomía"],
    ["name" => "Administración Turística", "title" => "Administración Turística"],
    ["name" => "Administración Hotelera", "title" => "Administración Hotelera"],
    ["name" => "Ciencias y Artes de la Hospitalidad Turismo", "title" => "Ciencias y Artes de la Hospitalidad Turismo"],
    ["name" => "Administración Hotelera y Ecoturismo", "title" => "Administración Hotelera y Ecoturismo"],
    ["name" => "Guía Oficial de Turismo", "title" => "Guía Oficial de Turismo"],
    ["name" => "Turismo y Negocios", "title" => "Turismo y Negocios"],
    ["name" => "Ingeniería en Turismo", "title" => "Ingeniería en Turismo"],
    ["name" => "Administración en Turismo", "title" => "Administración en Turismo"],
    ["name" => "Turismo, Hotelería y Gastronomía", "title" => "Turismo, Hotelería y Gastronomía"],
    ["name" => "Hotelería", "title" => "Hotelería"],
    ["name" => "Turismo y Hotelería", "title" => "Turismo y Hotelería"],
    ["name" => "Turismo", "title" => "Turismo"]
];

$GLOBALS['specialty_list'] = $specialty_list;


$grade_list = [
    ["name" => "Profesional Técnico", "title" => "Profesional Técnico"],
    ["name" => "Bachiller",           "title" => "Bachiller"],
    ["name" => "Doctorado",           "title" => "Doctorado"],
    ["name" => "Maestría",            "title" => "Maestría"],
    ["name" => "Titulado",            "title" => "Titulado"],
    ["name" => "Egresado",            "title" => "Egresado"],
    ["name" => "Estudiante",          "title" => "Estudiante"],
];

$GLOBALS['grade_list'] = $grade_list;




$keyword_list = [
    ["name" => "Administración",                     "title" => "Administración"],
    ["name" => "Comida",                             "title" => "Comida"],
    ["name" => "Docente de pre-grado",               "title" => "Docente de pre-grado"],
    ["name" => "Especialsita en planificación turística", "title" => "Especialsita en planificación turística"],
    ["name" => "Hotelería",                          "title" => "Hotelería"],
    ["name" => "Trabajo fuera de pais",              "title" => "Trabajo fuera de pais"],
];

$GLOBALS['keyword_list'] = $keyword_list;


$type_position_list = [
    ['name' => 'Técnico', 'title' => 'Técnico'],
    ['name' => 'Ejecutivo', 'title' => 'Ejecutivo'],
    ['name' => 'Voluntario', 'title' => 'Voluntario'],
    ['name' => 'Practicante', 'title' => 'Practicante'],
    ['name' => 'Asistente', 'title' => 'Asistente'],
    ['name' => 'Analista', 'title' => 'Analista'],
    ['name' => 'Especialista', 'title' => 'Especialista'],
    ['name' => 'Operario', 'title' => 'Operario'],
    ['name' => 'Supervisor', 'title' => 'Supervisor'],
    ['name' => 'Coordinador', 'title' => 'Coordinador'],
    ['name' => 'Administrador', 'title' => 'Administrador'],
    ['name' => 'Sub Gerente', 'title' => 'Sub Gerente'],
    ['name' => 'Gerente', 'title' => 'Gerente'],
    ['name' => 'Jefe', 'title' => 'Jefe'],
    ['name' => 'Director', 'title' => 'Director'],
];

$GLOBALS['type_position_list'] = $type_position_list;

$sector_list = [
    ['name' => 'Privado', 'title' => 'Privado'],
    ['name' => 'Publico', 'title' => 'Publico'],
];

$GLOBALS['sector_list'] = $sector_list;


$language_list = [
    ['name' => 'Noruego', 'title' => 'Noruego'],
    ['name' => 'Ucraniano', 'title' => 'Ucraniano'],
    ['name' => 'Búlgaro', 'title' => 'Búlgaro'],
    ['name' => 'Rumano', 'title' => 'Rumano'],
    ['name' => 'Esloveno', 'title' => 'Esloveno'],
    ['name' => 'Eslovaco', 'title' => 'Eslovaco'],
    ['name' => 'Maltés', 'title' => 'Maltés'],
    ['name' => 'Lituano', 'title' => 'Lituano'],
    ['name' => 'Letón', 'title' => 'Letón'],
    ['name' => 'Danés', 'title' => 'Danés'],
    ['name' => 'Hindi', 'title' => 'Hindi'],
    ['name' => 'Turco', 'title' => 'Turco'],
    ['name' => 'Sueco', 'title' => 'Sueco'],
    ['name' => 'Húngaro', 'title' => 'Húngaro'],
    ['name' => 'Holandés', 'title' => 'Holandés'],
    ['name' => 'Griego', 'title' => 'Griego'],
    ['name' => 'Galego', 'title' => 'Galego'],
    ['name' => 'Croata', 'title' => 'Croata'],
    ['name' => 'Checo', 'title' => 'Checo'],
    ['name' => 'Catalán', 'title' => 'Catalán'],
    ['name' => 'Quechua', 'title' => 'Quechua'],
    ['name' => 'Ruso', 'title' => 'Ruso'],
    ['name' => 'Portugués', 'title' => 'Portugués'],
    ['name' => 'Japonés', 'title' => 'Japonés'],
    ['name' => 'Italiano', 'title' => 'Italiano'],
    ['name' => 'Inglés', 'title' => 'Inglés'],
    ['name' => 'Francés', 'title' => 'Francés'],
    ['name' => 'Español', 'title' => 'Español'],
    ['name' => 'Coreano', 'title' => 'Coreano'],
    ['name' => 'Chino (Mandarín)', 'title' => 'Chino (Mandarín)'],
    ['name' => 'Árabe', 'title' => 'Árabe'],
    ['name' => 'Alemán', 'title' => 'Alemán'],
    ['name' => 'Aimara', 'title' => 'Aimara'],
];

$GLOBALS['language_list'] = $language_list;


$level_list = [
    ['name' => 'Nativo hablante', 'title' => 'Nativo hablante'],
    ['name' => 'Avanzado', 'title' => 'Avanzado'],
    ['name' => 'Intermedio', 'title' => 'Intermedio'],
    ['name' => 'Básico', 'title' => 'Básico'],
];

$GLOBALS['level_list'] = $level_list;


$skill_list = [
    ["name" => "Amadeus",        "title" => "Amadeus"],
    ["name" => "Diseño gráfico", "title" => "Diseño gráfico"],
    ["name" => "Diseño web",     "title" => "Diseño web"],
    ["name" => "Fotografía",     "title" => "Fotografía"],
    ["name" => "Galileo",        "title" => "Galileo"],
];

$institution_list = [
    ["name" => "Instituto de Educación Superior Tecnológico Público Purus", "title" => "Instituto de Educación Superior Tecnológico Público Purus"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Carlos Laborde", "title" => "Instituto de Educación Superior Tecnológico Público Carlos Laborde"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Padre Abad", "title" => "Instituto de Educación Superior Tecnológico Público Padre Abad"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Suiza", "title" => "Instituto de Educación Superior Tecnológico Público Suiza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Atalaya", "title" => "Instituto de Educación Superior Tecnológico Público Atalaya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Masisea", "title" => "Instituto de Educación Superior Tecnológico Público Masisea"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Colonia del Caco", "title" => "Instituto de Educación Superior Tecnológico Público Colonia del Caco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pablo Butz", "title" => "Instituto de Educación Superior Tecnológico Público Pablo Butz"],
    ["name" => "Instituto de Educación Superior Tecnológico Público 24 de julio de Zarumilla", "title" => "Instituto de Educación Superior Tecnológico Público 24 de julio de Zarumilla"],
    ["name" => "Instituto de Educación Superior Tecnológico Público CAP FAP José Abelardo Quiñones", "title" => "Instituto de Educación Superior Tecnológico Público CAP FAP José Abelardo Quiñones"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Contralmirante Manuel Villar Olivera", "title" => "Instituto de Educación Superior Tecnológico Público Contralmirante Manuel Villar Olivera"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Señor de Locumba", "title" => "Instituto de Educación Superior Tecnológico Público Señor de Locumba"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ramon Copaja", "title" => "Instituto de Educación Superior Tecnológico Público Ramon Copaja"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Francisco de Paula Gonzales Virgil", "title" => "Instituto de Educación Superior Tecnológico Público Francisco de Paula Gonzales Virgil"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nor Oriental de la Selva", "title" => "Instituto de Educación Superior Tecnológico Público Nor Oriental de la Selva"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huallaga", "title" => "Instituto de Educación Superior Tecnológico Público Huallaga"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Francisco Vigo Caballero", "title" => "Instituto de Educación Superior Tecnológico Público Francisco Vigo Caballero"],
    ["name" => "Instituto de Educación Superior Tecnológico Público El Dorado", "title" => "Instituto de Educación Superior Tecnológico Público El Dorado"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alto Huallaga", "title" => "Instituto de Educación Superior Tecnológico Público Alto Huallaga"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alto Mayo", "title" => "Instituto de Educación Superior Tecnológico Público Alto Mayo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Rioja", "title" => "Instituto de Educación Superior Tecnológico Público Rioja"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Bellavista", "title" => "Instituto de Educación Superior Tecnológico Público Bellavista"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Zepita", "title" => "Instituto de Educación Superior Tecnológico Público Zepita"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Salvador", "title" => "Instituto de Educación Superior Tecnológico Público San Salvador"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Juan del Oro", "title" => "Instituto de Educación Superior Tecnológico Público San Juan del Oro"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nuñoa", "title" => "Instituto de Educación Superior Tecnológico Público Nuñoa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Muñani", "title" => "Instituto de Educación Superior Tecnológico Público Muñani"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Mañazo", "title" => "Instituto de Educación Superior Tecnológico Público Mañazo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Macusani", "title" => "Instituto de Educación Superior Tecnológico Público Macusani"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Yunguyo", "title" => "Instituto de Educación Superior Tecnológico Público de Yunguyo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Cabanillas", "title" => "Instituto de Educación Superior Tecnológico Público de Cabanillas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ayaviri", "title" => "Instituto de Educación Superior Tecnológico Público Ayaviri"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Acora", "title" => "Instituto de Educación Superior Tecnológico Público Acora"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Núñez Butron", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Núñez Butron"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Andrés Avelino Cáceres", "title" => "Instituto de Educación Superior Tecnológico Público Andrés Avelino Cáceres"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pedro Vilcapaza", "title" => "Instituto de Educación Superior Tecnológico Público Pedro Vilcapaza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Desaguadero", "title" => "Instituto de Educación Superior Tecnológico Público Desaguadero"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santa Lucia", "title" => "Instituto de Educación Superior Tecnológico Público Santa Lucia"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Juli", "title" => "Instituto de Educación Superior Tecnológico Público Juli"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ilave", "title" => "Instituto de Educación Superior Tecnológico Público Ilave"],
    ["name" => "Instituto de Educación Superior Tecnológico Público José Antonio Encinas", "title" => "Instituto de Educación Superior Tecnológico Público José Antonio Encinas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público José Domingo Choquehuanca", "title" => "Instituto de Educación Superior Tecnológico Público José Domingo Choquehuanca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chupa", "title" => "Instituto de Educación Superior Tecnológico Público Chupa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huancané", "title" => "Instituto de Educación Superior Tecnológico Público Huancané"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santa Rosa", "title" => "Instituto de Educación Superior Tecnológico Público Santa Rosa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Sullana", "title" => "Instituto de Educación Superior Tecnológico Público Sullana"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Centro de Formación Profesional Binacional", "title" => "Instituto de Educación Superior Tecnológico Público Centro de Formación Profesional Binacional"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Juan José Farfán Céspedes", "title" => "Instituto de Educación Superior Tecnológico Público Juan José Farfán Céspedes"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Hermanos Cárcamo", "title" => "Instituto de Educación Superior Tecnológico Público Hermanos Cárcamo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Luis Felipe Agurto Olaya", "title" => "Instituto de Educación Superior Tecnológico Público Luis Felipe Agurto Olaya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Néstor Samuel Martos Garrido", "title" => "Instituto de Educación Superior Tecnológico Público Néstor Samuel Martos Garrido"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Andrés", "title" => "Instituto de Educación Superior Tecnológico Público San Andrés"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Lizardo Montero Flores", "title" => "Instituto de Educación Superior Tecnológico Público Lizardo Montero Flores"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Juan Esteban López Cruz", "title" => "Instituto de Educación Superior Tecnológico Público Juan Esteban López Cruz"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Señor de Chocán", "title" => "Instituto de Educación Superior Tecnológico Público Señor de Chocán"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Luciano Castillo Colonna", "title" => "Instituto de Educación Superior Tecnológico Público Luciano Castillo Colonna"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Vicus", "title" => "Instituto de Educación Superior Tecnológico Público Vicus"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ricardo Ramos Plata", "title" => "Instituto de Educación Superior Tecnológico Público Ricardo Ramos Plata"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Almirante Miguel Grau", "title" => "Instituto de Educación Superior Tecnológico Público Almirante Miguel Grau"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Morropón", "title" => "Instituto de Educación Superior Tecnológico Público Morropón"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Yarleque Espinoza", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Yarleque Espinoza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Canchaque", "title" => "Instituto de Educación Superior Tecnológico Público Canchaque"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huarmaca", "title" => "Instituto de Educación Superior Tecnológico Público Huarmaca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ayabaca", "title" => "Instituto de Educación Superior Tecnológico Público Ayabaca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pasco", "title" => "Instituto de Educación Superior Tecnológico Público Pasco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Rodrigo Salazar Palacios", "title" => "Instituto de Educación Superior Tecnológico Público Rodrigo Salazar Palacios"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Paucartambo", "title" => "Instituto de Educación Superior Tecnológico Público Paucartambo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Oxapampa", "title" => "Instituto de Educación Superior Tecnológico Público Oxapampa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Daniel Alcides Carrión", "title" => "Instituto de Educación Superior Tecnológico Público Daniel Alcides Carrión"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alfred Nobel", "title" => "Instituto de Educación Superior Tecnológico Público Alfred Nobel"],
    ["name" => "Instituto de Educación Superior Tecnológico Privado Alexander Von Humboldt", "title" => "Instituto de Educación Superior Tecnológico Privado Alexander Von Humboldt"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alberto Pumaylla Diaz", "title" => "Instituto de Educación Superior Tecnológico Público Alberto Pumaylla Diaz"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alianza Renovada Ichuña Bélgica", "title" => "Instituto de Educación Superior Tecnológico Público Alianza Renovada Ichuña Bélgica"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chojata", "title" => "Instituto de Educación Superior Tecnológico Público Chojata"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Inmaculada Concepción", "title" => "Instituto de Educación Superior Tecnológico Público Inmaculada Concepción"],
    ["name" => "Instituto de Educación Superior Tecnológico Público José Carlos Mariátegui", "title" => "Instituto de Educación Superior Tecnológico Público José Carlos Mariátegui"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Omate", "title" => "Instituto de Educación Superior Tecnológico Público Omate"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Centro de Formación Agrícola de Moquegua", "title" => "Instituto de Educación Superior Tecnológico Público Centro de Formación Agrícola de Moquegua"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Luis E. Valcárcel", "title" => "Instituto de Educación Superior Tecnológico Público Luis E. Valcárcel"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de los Andes", "title" => "Instituto de Educación Superior Tecnológico Público de los Andes"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Jorge Basadre Grohman", "title" => "Instituto de Educación Superior Tecnológico Público Jorge Basadre Grohman"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Iberia - Tahuamanu", "title" => "Instituto de Educación Superior Tecnológico Público Iberia - Tahuamanu"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manu", "title" => "Instituto de Educación Superior Tecnológico Público Manu"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Lorenzo", "title" => "Instituto de Educación Superior Tecnológico Público San Lorenzo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pedro A. del Águila Hidalgo", "title" => "Instituto de Educación Superior Tecnológico Público Pedro A. del Águila Hidalgo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Mariscal Ramon Castilla", "title" => "Instituto de Educación Superior Tecnológico Público Mariscal Ramon Castilla"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manos Unidas", "title" => "Instituto de Educación Superior Tecnológico Público Manos Unidas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Leónidas Lopez Chicae", "title" => "Instituto de Educación Superior Tecnológico Público Leónidas Lopez Chicae"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Lagunas", "title" => "Instituto de Educación Superior Tecnológico Público Lagunas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Joaquín Reátegui Medina", "title" => "Instituto de Educación Superior Tecnológico Público Joaquín Reátegui Medina"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Fernando Lores Tenazoa", "title" => "Instituto de Educación Superior Tecnológico Público Fernando Lores Tenazoa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público El Milagro", "title" => "Instituto de Educación Superior Tecnológico Público El Milagro"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de el Estrecho Río Putumayo", "title" => "Instituto de Educación Superior Tecnológico Público de el Estrecho Río Putumayo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Damaso Laberge", "title" => "Instituto de Educación Superior Tecnológico Público Damaso Laberge"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Contamana", "title" => "Instituto de Educación Superior Tecnológico Público Contamana"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Amazonas - Yurimaguas", "title" => "Instituto de Educación Superior Tecnológico Público Amazonas - Yurimaguas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Fe y Alegria 61 - Santa Rafaela María", "title" => "Instituto de Educación Superior Tecnológico Público Fe y Alegria 61 - Santa Rafaela María"],
    ["name" => "Instituto de Educación Superior Tecnológico Público fe y Alegría 75", "title" => "Instituto de Educación Superior Tecnológico Público fe y Alegría 75"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Magda Portal", "title" => "Instituto de Educación Superior Tecnológico Público Magda Portal"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Canta", "title" => "Instituto de Educación Superior Tecnológico Público Canta"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Arévalo Cáceres", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Arévalo Cáceres"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Carlos Cueto Fernandini", "title" => "Instituto de Educación Superior Tecnológico Público Carlos Cueto Fernandini"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Luis Negreiros Vega", "title" => "Instituto de Educación Superior Tecnológico Público Luis Negreiros Vega"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Diseño y Comunicación", "title" => "Instituto de Educación Superior Tecnológico Público Diseño y Comunicación"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Naciones Unidas", "title" => "Instituto de Educación Superior Tecnológico Público Naciones Unidas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santa María Magdalena", "title" => "Instituto de Educación Superior Tecnológico Público Santa María Magdalena"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pacaraos", "title" => "Instituto de Educación Superior Tecnológico Público Pacaraos"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Jatum Yauyos", "title" => "Instituto de Educación Superior Tecnológico Público Jatum Yauyos"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Oyon", "title" => "Instituto de Educación Superior Tecnológico Público Oyon"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Arturo Sabroso Montoya", "title" => "Instituto de Educación Superior Tecnológico Público Arturo Sabroso Montoya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Misioneros Monfortianos", "title" => "Instituto de Educación Superior Tecnológico Público Misioneros Monfortianos"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Hilda Liliana Ballivián Rosado", "title" => "Instituto de Educación Superior Tecnológico Público Hilda Liliana Ballivián Rosado"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nicanor Mujica Álvarez Calderón", "title" => "Instituto de Educación Superior Tecnológico Público Nicanor Mujica Álvarez Calderón"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Julio Cesar Tello", "title" => "Instituto de Educación Superior Tecnológico Público Julio Cesar Tello"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Amauta Julio C. Tello", "title" => "Instituto de Educación Superior Tecnológico Público Amauta Julio C. Tello"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Villa María", "title" => "Instituto de Educación Superior Tecnológico Público Villa María"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pacaran", "title" => "Instituto de Educación Superior Tecnológico Público Pacaran"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Argentina", "title" => "Instituto de Educación Superior Tecnológico Público Argentina"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Francisco de Asís", "title" => "Instituto de Educación Superior Tecnológico Público San Francisco de Asís"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chancay", "title" => "Instituto de Educación Superior Tecnológico Público Chancay"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Antenor Orrego Espinoza", "title" => "Instituto de Educación Superior Tecnológico Público Antenor Orrego Espinoza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Pedro del Valle de Mala", "title" => "Instituto de Educación Superior Tecnológico Público San Pedro del Valle de Mala"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Cañete", "title" => "Instituto de Educación Superior Tecnológico Público Cañete"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Seoane Corrales", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Seoane Corrales"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Juan Velasco Alvarado", "title" => "Instituto de Educación Superior Tecnológico Público Juan Velasco Alvarado"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ramiro Priale Priale", "title" => "Instituto de Educación Superior Tecnológico Público Ramiro Priale Priale"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Lurín", "title" => "Instituto de Educación Superior Tecnológico Público Lurín"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huaycán", "title" => "Instituto de Educación Superior Tecnológico Público Huaycán"],
    ["name" => "Instituto de Educación Superior Tecnológico Público María Rosario Araoz Pinto", "title" => "Instituto de Educación Superior Tecnológico Público María Rosario Araoz Pinto"],
    ["name" => "Instituto de Educación Superior Tecnológico Público José Pardo", "title" => "Instituto de Educación Superior Tecnológico Público José Pardo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Enrique Lopez Albujar", "title" => "Instituto de Educación Superior Tecnológico Público Enrique Lopez Albujar"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Olmos", "title" => "Instituto de Educación Superior Tecnológico Público Olmos"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Illimo", "title" => "Instituto de Educación Superior Tecnológico Público Illimo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ciudad Eten", "title" => "Instituto de Educación Superior Tecnológico Público Ciudad Eten"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Monsefú", "title" => "Instituto de Educación Superior Tecnológico Público Monsefú"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Yatraywasi", "title" => "Instituto de Educación Superior Tecnológico Público Yatraywasi"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Motupe", "title" => "Instituto de Educación Superior Tecnológico Público Motupe"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pascual Sacoy Oliveros", "title" => "Instituto de Educación Superior Tecnológico Público Pascual Sacoy Oliveros"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Edilberto Rivas Vásquez", "title" => "Instituto de Educación Superior Tecnológico Público Edilberto Rivas Vásquez"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Republica Federal de Alemania", "title" => "Instituto de Educación Superior Tecnológico Público Republica Federal de Alemania"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chongoyape", "title" => "Instituto de Educación Superior Tecnológico Público Chongoyape"],
    ["name" => "Instituto de Educación Superior Tecnológico Público CEFOP La Libertad", "title" => "Instituto de Educación Superior Tecnológico Público CEFOP La Libertad"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chillia", "title" => "Instituto de Educación Superior Tecnológico Público Chillia"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Victor Andrés Belaunde", "title" => "Instituto de Educación Superior Tecnológico Público Victor Andrés Belaunde"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Simón Sanchez Reyes", "title" => "Instituto de Educación Superior Tecnológico Público Simón Sanchez Reyes"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huancaspata", "title" => "Instituto de Educación Superior Tecnológico Público Huancaspata"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Erasmo Arellano Guillen", "title" => "Instituto de Educación Superior Tecnológico Público Erasmo Arellano Guillen"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Virú", "title" => "Instituto de Educación Superior Tecnológico Público Virú"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Otuzco", "title" => "Instituto de Educación Superior Tecnológico Público Otuzco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ciro Alegría Bazán", "title" => "Instituto de Educación Superior Tecnológico Público Ciro Alegría Bazán"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Héctor Vásquez Jiménez", "title" => "Instituto de Educación Superior Tecnológico Público Héctor Vásquez Jiménez"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Bolívar", "title" => "Instituto de Educación Superior Tecnológico Público Bolívar"],
    ["name" => "Instituto de Educación Superior Pedagógico Público Manuel Gonzales Padra", "title" => "Instituto de Educación Superior Pedagógico Público Manuel Gonzales Padra"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nueva Esperanza", "title" => "Instituto de Educación Superior Tecnológico Público Nueva Esperanza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Laredo", "title" => "Instituto de Educación Superior Tecnológico Público Laredo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Trujillo", "title" => "Instituto de Educación Superior Tecnológico Público Trujillo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Jorge Desmaison Seminario", "title" => "Instituto de Educación Superior Tecnológico Público Jorge Desmaison Seminario"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Paijan", "title" => "Instituto de Educación Superior Tecnológico Público Paijan"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Jesús Diaz Murrugarra", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Jesús Diaz Murrugarra"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Mache", "title" => "Instituto de Educación Superior Tecnológico Público Mache"],
    ["name" => "Instituto de Educación Superior Pedagógico Privado Liberdad", "title" => "Instituto de Educación Superior Pedagógico Privado Liberdad"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Florencia de Mora", "title" => "Instituto de Educación Superior Tecnológico Público Florencia de Mora"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Guadalupe", "title" => "Instituto de Educación Superior Tecnológico Público Guadalupe"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huamachuco", "title" => "Instituto de Educación Superior Tecnológico Público Huamachuco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Victor Raúl Haya de la Torre", "title" => "Instituto de Educación Superior Tecnológico Público Victor Raúl Haya de la Torre"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chocope", "title" => "Instituto de Educación Superior Tecnológico Público Chocope"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Taurija", "title" => "Instituto de Educación Superior Tecnológico Público Taurija"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ascope", "title" => "Instituto de Educación Superior Tecnológico Público Ascope"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pichanaki", "title" => "Instituto de Educación Superior Tecnológico Público Pichanaki"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Meseta de Bombón", "title" => "Instituto de Educación Superior Tecnológico Público Meseta de Bombón"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Adolfo Vienrich", "title" => "Instituto de Educación Superior Tecnológico Público Adolfo Vienrich"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Mario Gutiérrez Lopez", "title" => "Instituto de Educación Superior Tecnológico Público Mario Gutiérrez Lopez"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Puerto Libre", "title" => "Instituto de Educación Superior Tecnológico Público Puerto Libre"],
    ["name" => "Instituto de Educación Superior Tecnológico Público La Merced", "title" => "Instituto de Educación Superior Tecnológico Público La Merced"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Teodoro Rivera Taype", "title" => "Instituto de Educación Superior Tecnológico Público Teodoro Rivera Taype"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Andrés Avelino Cáceres Dorregaray", "title" => "Instituto de Educación Superior Tecnológico Público Andrés Avelino Cáceres Dorregaray"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Martin de Pangoa", "title" => "Instituto de Educación Superior Tecnológico Público San Martin de Pangoa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santiago Antúnez de Mayolo", "title" => "Instituto de Educación Superior Tecnológico Público Santiago Antúnez de Mayolo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Ashaninka", "title" => "Instituto de Educación Superior Tecnológico Público Ashaninka"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Jaime Cerrón Palomino", "title" => "Instituto de Educación Superior Tecnológico Público Jaime Cerrón Palomino"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Héroes de Sierra Lumi", "title" => "Instituto de Educación Superior Tecnológico Público Héroes de Sierra Lumi"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Marco", "title" => "Instituto de Educación Superior Tecnológico Público Marco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Concepción", "title" => "Instituto de Educación Superior Tecnológico Público de Concepción"],
    ["name" => "Instituto de Educación Superior Tecnológico Público La Oroya", "title" => "Instituto de Educación Superior Tecnológico Público La Oroya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Ignacio de Loyola", "title" => "Instituto de Educación Superior Tecnológico Público San Ignacio de Loyola"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Sausa", "title" => "Instituto de Educación Superior Tecnológico Público Sausa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Canipaco", "title" => "Instituto de Educación Superior Tecnológico Público Canipaco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Catalina Buendía de Pecho", "title" => "Instituto de Educación Superior Tecnológico Público Catalina Buendía de Pecho"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Luis Felipe de las Casas Grieve", "title" => "Instituto de Educación Superior Tecnológico Público Luis Felipe de las Casas Grieve"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pisco", "title" => "Instituto de Educación Superior Tecnológico Público Pisco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Fernando León de Vivero", "title" => "Instituto de Educación Superior Tecnológico Público Fernando León de Vivero"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nasca", "title" => "Instituto de Educación Superior Tecnológico Público Nasca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Chincha", "title" => "Instituto de Educación Superior Tecnológico Público de Chincha"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Palpa", "title" => "Instituto de Educación Superior Tecnológico Público Palpa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Tinyash", "title" => "Instituto de Educación Superior Tecnológico Público Tinyash"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Naranjillo", "title" => "Instituto de Educación Superior Tecnológico Público Naranjillo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Glicerio Gómez Igarza", "title" => "Instituto de Educación Superior Tecnológico Público Glicerio Gómez Igarza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Felipe Huamán Poma de Alaya", "title" => "Instituto de Educación Superior Tecnológico Público Felipe Huamán Poma de Alaya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Mariano Bonin", "title" => "Instituto de Educación Superior Tecnológico Público Mariano Bonin"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Puerto Inca", "title" => "Instituto de Educación Superior Tecnológico Público Puerto Inca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Javier Pulgar Vidal", "title" => "Instituto de Educación Superior Tecnológico Público Javier Pulgar Vidal"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Aparicio Pomares", "title" => "Instituto de Educación Superior Tecnológico Público Aparicio Pomares"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Virgen de Cocharcas", "title" => "Instituto de Educación Superior Tecnológico Público Virgen de Cocharcas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Juan Bautista", "title" => "Instituto de Educación Superior Tecnológico Público San Juan Bautista"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San José", "title" => "Instituto de Educación Superior Tecnológico Público San José"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Paucará", "title" => "Instituto de Educación Superior Tecnológico Público Paucará"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nuevo Occoro", "title" => "Instituto de Educación Superior Tecnológico Público Nuevo Occoro"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Lircay", "title" => "Instituto de Educación Superior Tecnológico Público Lircay"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Colcabamba", "title" => "Instituto de Educación Superior Tecnológico Público Colcabamba"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Ticrapo", "title" => "Instituto de Educación Superior Tecnológico Público de Ticrapo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Scorza Torre", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Scorza Torre"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huancavelica", "title" => "Instituto de Educación Superior Tecnológico Público Huancavelica"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Churcampa", "title" => "Instituto de Educación Superior Tecnológico Público Churcampa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Aurahuá", "title" => "Instituto de Educación Superior Tecnológico Público Aurahuá"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Velille", "title" => "Instituto de Educación Superior Tecnológico Público Velille"],
    ["name" => "Instituto de Educación Superior Tecnológico Público La Salle", "title" => "Instituto de Educación Superior Tecnológico Público La Salle"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Kimbiri", "title" => "Instituto de Educación Superior Tecnológico Público Kimbiri"],
    ["name" => "Instituto de Educación Superior Tecnológico Público El Descanso", "title" => "Instituto de Educación Superior Tecnológico Público El Descanso"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Enrique Pablo Mejía Tupayachi", "title" => "Instituto de Educación Superior Tecnológico Público Enrique Pablo Mejía Tupayachi"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Divino Jesús", "title" => "Instituto de Educación Superior Tecnológico Público Divino Jesús"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Vilcanota", "title" => "Instituto de Educación Superior Tecnológico Público Vilcanota"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Tupac Amaru", "title" => "Instituto de Educación Superior Tecnológico Público Tupac Amaru"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Clorinda Matto de Turner", "title" => "Instituto de Educación Superior Tecnológico Público Clorinda Matto de Turner"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Sangarara", "title" => "Instituto de Educación Superior Tecnológico Público Sangarara"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Espinar", "title" => "Instituto de Educación Superior Tecnológico Público de Espinar"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Anta", "title" => "Instituto de Educación Superior Tecnológico Público Anta"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Simón Bolívar", "title" => "Instituto de Educación Superior Tecnológico Público Simón Bolívar"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santo Villalobos Huamán", "title" => "Instituto de Educación Superior Tecnológico Público Santo Villalobos Huamán"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Querocoto", "title" => "Instituto de Educación Superior Tecnológico Público Querocoto"],
    ["name" => "Instituto de Educación Superior Tecnológico Público pedro Ortiz Montoya", "title" => "Instituto de Educación Superior Tecnológico Público pedro Ortiz Montoya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chalamarca", "title" => "Instituto de Educación Superior Tecnológico Público Chalamarca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público CEFOP Cajamarca", "title" => "Instituto de Educación Superior Tecnológico Público CEFOP Cajamarca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Bambamarca", "title" => "Instituto de Educación Superior Tecnológico Público Bambamarca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Tembladera", "title" => "Instituto de Educación Superior Tecnológico Público Tembladera"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Felipe Alva y Alva", "title" => "Instituto de Educación Superior Tecnológico Público Felipe Alva y Alva"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alfredo José María Rocha Zegarra", "title" => "Instituto de Educación Superior Tecnológico Público Alfredo José María Rocha Zegarra"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Ignacio", "title" => "Instituto de Educación Superior Tecnológico Público San Ignacio"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Marcos de Cajamarca", "title" => "Instituto de Educación Superior Tecnológico Público San Marcos de Cajamarca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Agustín", "title" => "Instituto de Educación Superior Tecnológico Público San Agustín"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Cajamarca", "title" => "Instituto de Educación Superior Tecnológico Público Cajamarca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Cutervo", "title" => "Instituto de Educación Superior Tecnológico Público Cutervo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Nuestra Señora de las Mercedes", "title" => "Instituto de Educación Superior Tecnológico Público Nuestra Señora de las Mercedes"],
    ["name" => "Instituto de Educación Superior Tecnológico Público 4 de junio de 1821", "title" => "Instituto de Educación Superior Tecnológico Público 4 de junio de 1821"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chota", "title" => "Instituto de Educación Superior Tecnológico Público Chota"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Carlos Malpica Rivarola", "title" => "Instituto de Educación Superior Tecnológico Público Carlos Malpica Rivarola"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Virgen del Rosario", "title" => "Instituto de Educación Superior Tecnológico Público Virgen del Rosario"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Víctor Álvarez Huapaya", "title" => "Instituto de Educación Superior Tecnológico Público Víctor Álvarez Huapaya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santo Domingo de Guzmán", "title" => "Instituto de Educación Superior Tecnológico Público Santo Domingo de Guzmán"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Miguel", "title" => "Instituto de Educación Superior Tecnológico Público San Miguel"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Juan", "title" => "Instituto de Educación Superior Tecnológico Público San Juan"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Perú Corea del Sur", "title" => "Instituto de Educación Superior Tecnológico Público Perú Corea del Sur"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Paucar del Sarasara", "title" => "Instituto de Educación Superior Tecnológico Público Paucar del Sarasara"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Los Morochucos", "title" => "Instituto de Educación Superior Tecnológico Público Los Morochucos"],
    ["name" => "Instituto de Educación Superior Tecnológico Público José Maria Arguedas", "title" => "Instituto de Educación Superior Tecnológico Público José Maria Arguedas"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Huanta", "title" => "Instituto de Educación Superior Tecnológico Público Huanta"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Hatun Soras", "title" => "Instituto de Educación Superior Tecnológico Público Hatun Soras"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Federico Gonzales Cabezudo", "title" => "Instituto de Educación Superior Tecnológico Público Federico Gonzales Cabezudo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Cesar Augusto Guardia Mayorca", "title" => "Instituto de Educación Superior Tecnológico Público Cesar Augusto Guardia Mayorca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Aucará", "title" => "Instituto de Educación Superior Tecnológico Público Aucará"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chipao", "title" => "Instituto de Educación Superior Tecnológico Público Chipao"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Manuel Antonio Hierro Pozo", "title" => "Instituto de Educación Superior Tecnológico Público Manuel Antonio Hierro Pozo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Peruano Español", "title" => "Instituto de Educación Superior Tecnológico Público Peruano Español"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chala", "title" => "Instituto de Educación Superior Tecnológico Público Chala"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chuquibamba", "title" => "Instituto de Educación Superior Tecnológico Público Chuquibamba"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Monseñor Julio Gonzales Ruiz", "title" => "Instituto de Educación Superior Tecnológico Público Monseñor Julio Gonzales Ruiz"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Castilla", "title" => "Instituto de Educación Superior Tecnológico Público Castilla"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Yanque", "title" => "Instituto de Educación Superior Tecnológico Público Yanque"],
    ["name" => "Instituto de Educación Superior Tecnológico La Recoleta", "title" => "Instituto de Educación Superior Tecnológico La Recoleta"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Valle de Tambo", "title" => "Instituto de Educación Superior Tecnológico Público Valle de Tambo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Faustino B. Franco", "title" => "Instituto de Educación Superior Tecnológico Público Faustino B. Franco"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Honorio Delgado Espinoza", "title" => "Instituto de Educación Superior Tecnológico Público Honorio Delgado Espinoza"],
    ["name" => "Instituto de Educación Superior Pedagógico Público Jorge Basadre", "title" => "Instituto de Educación Superior Pedagógico Público Jorge Basadre"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chivay", "title" => "Instituto de Educación Superior Tecnológico Público Chivay"],
    ["name" => "Instituto de Educación Superior Tecnológico Público La Joya", "title" => "Instituto de Educación Superior Tecnológico Público La Joya"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Pedro P. Diaz", "title" => "Instituto de Educación Superior Tecnológico Público Pedro P. Diaz"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Vilcabamba", "title" => "Instituto de Educación Superior Tecnológico Público de Vilcabamba"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Todas las Artes", "title" => "Instituto de Educación Superior Tecnológico Público Todas las Artes"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Huaccana", "title" => "Instituto de Educación Superior Tecnológico Público de Huaccana"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Hermenegildo Miranda Segovia", "title" => "Instituto de Educación Superior Tecnológico Público Hermenegildo Miranda Segovia"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Haquira", "title" => "Instituto de Educación Superior Tecnológico Público Haquira"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Chincheros", "title" => "Instituto de Educación Superior Tecnológico Público de Chincheros"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Chalhuanca", "title" => "Instituto de Educación Superior Tecnológico Público Chalhuanca"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Challhuahuacho", "title" => "Instituto de Educación Superior Tecnológico Público Challhuahuacho"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Abancay", "title" => "Instituto de Educación Superior Tecnológico Público Abancay"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Alfredo Sarmiento Palomino", "title" => "Instituto de Educación Superior Tecnológico Público Alfredo Sarmiento Palomino"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Curahuasi", "title" => "Instituto de Educación Superior Tecnológico Público Curahuasi"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Marcos", "title" => "Instituto de Educación Superior Tecnológico Público San Marcos"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Luis", "title" => "Instituto de Educación Superior Tecnológico Público San Luis"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Narciso Villanueva Manzo", "title" => "Instituto de Educación Superior Tecnológico Público Narciso Villanueva Manzo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Progreso", "title" => "Instituto de Educación Superior Tecnológico Público Progreso"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Copacabana de Llapo", "title" => "Instituto de Educación Superior Tecnológico Público Copacabana de Llapo"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Huarmey", "title" => "Instituto de Educación Superior Tecnológico Público de Huarmey"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Aija", "title" => "Instituto de Educación Superior Tecnológico Público Aija"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Río Santa", "title" => "Instituto de Educación Superior Tecnológico Público Río Santa"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Piscobamba", "title" => "Instituto de Educación Superior Tecnológico Público de Piscobamba"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Daniel Villar", "title" => "Instituto de Educación Superior Tecnológico Público Daniel Villar"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Pedro", "title" => "Instituto de Educación Superior Tecnológico Público San Pedro"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Carlos Salazar Romero", "title" => "Instituto de Educación Superior Tecnológico Público Carlos Salazar Romero"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Cabana", "title" => "Instituto de Educación Superior Tecnológico Público Cabana"],
    ["name" => "Instituto de Educación Superior Tecnológico Público San Nicolás", "title" => "Instituto de Educación Superior Tecnológico Público San Nicolás"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Virgen de Guadalupe", "title" => "Instituto de Educación Superior Tecnológico Público Virgen de Guadalupe"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Juan Huarín de Huari", "title" => "Instituto de Educación Superior Tecnológico Público Juan Huarín de Huari"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Carhuaz", "title" => "Instituto de Educación Superior Tecnológico Público Carhuaz"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Señor de la Divina Misericordia", "title" => "Instituto de Educación Superior Tecnológico Público Señor de la Divina Misericordia"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Llamellin", "title" => "Instituto de Educación Superior Tecnológico Público Llamellin"],
    ["name" => "Instituto de Educación Superior Tecnológico Público de Casma", "title" => "Instituto de Educación Superior Tecnológico Público de Casma"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Agustín Haya de la Torre", "title" => "Instituto de Educación Superior Tecnológico Público Agustín Haya de la Torre"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Recuay", "title" => "Instituto de Educación Superior Tecnológico Público Recuay"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Eleazar Guzmán Barrón", "title" => "Instituto de Educación Superior Tecnológico Público Eleazar Guzmán Barrón"],
    ["name" => "Instituto de Educación Superior Pedagógico Privado Antonio Raymondi", "title" => "Instituto de Educación Superior Pedagógico Privado Antonio Raymondi"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Santa María de Nieva - Fe y Alegría 74", "title" => "Instituto de Educación Superior Tecnológico Público Santa María de Nieva - Fe y Alegría 74"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Señor de Gualamita", "title" => "Instituto de Educación Superior Tecnológico Público Señor de Gualamita"],
    ["name" => "Instituto de Educación Superior Tecnológico Gustavo Eduardo Lanatta Lujan", "title" => "Instituto de Educación Superior Tecnológico Gustavo Eduardo Lanatta Lujan"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Perú Japón", "title" => "Instituto de Educación Superior Tecnológico Público Perú Japón"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Rodríguez de Mendoza", "title" => "Instituto de Educación Superior Tecnológico Público Rodríguez de Mendoza"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Lonya Grande", "title" => "Instituto de Educación Superior Tecnológico Público Lonya Grande"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Bagua", "title" => "Instituto de Educación Superior Tecnológico Público Bagua"],
    ["name" => "Instituto de Educación Superior Tecnológico Público Tsamajain", "title" => "Instituto de Educación Superior Tecnológico Público Tsamajain"],
    ["name" => "Universidad Nacional de la Amazonía Peruana", "title" => "Universidad Nacional de la Amazonía Peruana"],
    ["name" => "Universidad Nacional Autónoma de Alto Amazonas", "title" => "Universidad Nacional Autónoma de Alto Amazonas"],
    ["name" => "Universidad Privada de la Selva Peruana", "title" => "Universidad Privada de la Selva Peruana"],
    ["name" => "Universidad Peruana del Oriente", "title" => "Universidad Peruana del Oriente"],
    ["name" => "Universidad Científica del Perú", "title" => "Universidad Científica del Perú"],
    ["name" => "Universidad Nacional Intercultural de la Amazonía", "title" => "Universidad Nacional Intercultural de la Amazonía"],
    ["name" => "Universidad Nacional de Ucayali", "title" => "Universidad Nacional de Ucayali"],
    ["name" => "Universidad Privada de Pucallpa", "title" => "Universidad Privada de Pucallpa"],
    ["name" => "Universidad Nacional Amazónica de Madre de Dios", "title" => "Universidad Nacional Amazónica de Madre de Dios"],
    ["name" => "Universidad Nacional de Huancavelica", "title" => "Universidad Nacional de Huancavelica"],
    ["name" => "Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo", "title" => "Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo"],
    ["name" => "Universidad para el Desarrollo Andino", "title" => "Universidad para el Desarrollo Andino"],
    ["name" => "Universidad Nacional Daniel Alcides Carrión", "title" => "Universidad Nacional Daniel Alcides Carrión"],
    ["name" => "Universidad Nacional Hermilio Valdizán", "title" => "Universidad Nacional Hermilio Valdizán"],
    ["name" => "Universidad Nacional Agraria de la Selva", "title" => "Universidad Nacional Agraria de la Selva"],
    ["name" => "Universidad de Huánuco", "title" => "Universidad de Huánuco"],
    ["name" => "Universidad Nacional de San Martín", "title" => "Universidad Nacional de San Martín"],
    ["name" => "Universidad Politécnica Amazónica S.A.C.", "title" => "Universidad Politécnica Amazónica S.A.C."],
    ["name" => "Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas", "title" => "Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas"],
    ["name" => "Universidad Nacional Intercultural Fabiola Salazar Leguía de Bagua", "title" => "Universidad Nacional Intercultural Fabiola Salazar Leguía de Bagua"],
    ["name" => "Universidad Peruana Los Andes", "title" => "Universidad Peruana Los Andes"],
    ["name" => "Universidad Continental", "title" => "Universidad Continental"],
    ["name" => "Universidad Peruana del Centro", "title" => "Universidad Peruana del Centro"],
    ["name" => "Universidad Privada de Huancayo Franklin Roosevelt", "title" => "Universidad Privada de Huancayo Franklin Roosevelt"],
    ["name" => "Universidad Santo Tomás de Aquino de Ciencia e Integración", "title" => "Universidad Santo Tomás de Aquino de Ciencia e Integración"],
    ["name" => "Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa", "title" => "Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa"],
    ["name" => "Universidad Nacional del Centro del Perú", "title" => "Universidad Nacional del Centro del Perú"],
    ["name" => "Universidad Nacional Autónoma Altoandina de Tarma", "title" => "Universidad Nacional Autónoma Altoandina de Tarma"],
    ["name" => "Universidad Nacional de Jaén", "title" => "Universidad Nacional de Jaén"],
    ["name" => "Universidad Nacional de Cajamarca", "title" => "Universidad Nacional de Cajamarca"],
    ["name" => "Universidad Nacional Autónoma de Chota", "title" => "Universidad Nacional Autónoma de Chota"],
    ["name" => "Universidad Privada Antonio Guillermo Urrelo", "title" => "Universidad Privada Antonio Guillermo Urrelo"],
    ["name" => "Universidad Tecnológica de los Andes", "title" => "Universidad Tecnológica de los Andes"],
    ["name" => "Universidad Nacional Micaela Bastidas de Apurímac", "title" => "Universidad Nacional Micaela Bastidas de Apurímac"],
    ["name" => "Universidad Nacional José María Arguedas", "title" => "Universidad Nacional José María Arguedas"],
    ["name" => "Universidad Nacional del Altiplano", "title" => "Universidad Nacional del Altiplano"],
    ["name" => "Universidad Nacional de Juliaca", "title" => "Universidad Nacional de Juliaca"],
    ["name" => "Universidad Privada San Carlos", "title" => "Universidad Privada San Carlos"],
    ["name" => "Universidad Andina Néstor Cáceres Velásquez", "title" => "Universidad Andina Néstor Cáceres Velásquez"],
    ["name" => "Universidad Latinoamericana CIMA", "title" => "Universidad Latinoamericana CIMA"],
    ["name" => "Universidad Privada de Tacna", "title" => "Universidad Privada de Tacna"],
    ["name" => "Escuela de Posgrado Newman", "title" => "Escuela de Posgrado Newman"],
    ["name" => "Universidad Nacional Jorge Basadre Grohmann", "title" => "Universidad Nacional Jorge Basadre Grohmann"],
    ["name" => "Universidad José Carlos Mariátegui", "title" => "Universidad José Carlos Mariátegui"],
    ["name" => "Universidad Nacional de Moquegua", "title" => "Universidad Nacional de Moquegua"],
    ["name" => "Universidad Nacional de San Agustín de Arequipa", "title" => "Universidad Nacional de San Agustín de Arequipa"],
    ["name" => "Universidad Privada Autónoma del Sur", "title" => "Universidad Privada Autónoma del Sur"],
    ["name" => "Universidad La Salle", "title" => "Universidad La Salle"],
    ["name" => "Universidad Autónoma San Francisco", "title" => "Universidad Autónoma San Francisco"],
    ["name" => "Universidad Ciencias de la Salud", "title" => "Universidad Ciencias de la Salud"],
    ["name" => "Universidad Católica San Pablo", "title" => "Universidad Católica San Pablo"],
    ["name" => "Universidad Católica de Santa María", "title" => "Universidad Católica de Santa María"],
    ["name" => "Universidad Nacional Santiago Antúnez de Mayolo", "title" => "Universidad Nacional Santiago Antúnez de Mayolo"],
    ["name" => "Universidad Católica Los Ángeles de Chimbote", "title" => "Universidad Católica Los Ángeles de Chimbote"],
    ["name" => "Universidad San Pedro", "title" => "Universidad San Pedro"],
    ["name" => "Universidad Nacional del Santa", "title" => "Universidad Nacional del Santa"],
    ["name" => "Universidad Nacional de Tumbes", "title" => "Universidad Nacional de Tumbes"],
    ["name" => "Universidad Nacional de Piura", "title" => "Universidad Nacional de Piura"],
    ["name" => "Universidad Nacional de Frontera", "title" => "Universidad Nacional de Frontera"],
    ["name" => "Universidad de Piura", "title" => "Universidad de Piura"],
    ["name" => "Universidad de Lambayeque", "title" => "Universidad de Lambayeque"],
    ["name" => "Universidad Nacional Pedro Ruiz Gallo", "title" => "Universidad Nacional Pedro Ruiz Gallo"],
    ["name" => "Universidad Privada Juan Mejía Baca", "title" => "Universidad Privada Juan Mejía Baca"],
    ["name" => "Universidad Señor de Sipán", "title" => "Universidad Señor de Sipán"],
    ["name" => "Universidad Católica Santo Toribio de Mogrovejo", "title" => "Universidad Católica Santo Toribio de Mogrovejo"],
    ["name" => "Universidad Particular de Chiclayo", "title" => "Universidad Particular de Chiclayo"],
    ["name" => "Universidad Privada Leonardo Da Vinci", "title" => "Universidad Privada Leonardo Da Vinci"],
    ["name" => "Universidad Privada de Trujillo", "title" => "Universidad Privada de Trujillo"],
    ["name" => "Universidad Católica de Trujillo Benedicto XVI", "title" => "Universidad Católica de Trujillo Benedicto XVI"],
    ["name" => "Universidad Privada del Norte", "title" => "Universidad Privada del Norte"],
    ["name" => "Universidad César Vallejo", "title" => "Universidad César Vallejo"],
    ["name" => "Universidad Privada Antenor Orrego", "title" => "Universidad Privada Antenor Orrego"],
    ["name" => "Universidad Nacional de Trujillo", "title" => "Universidad Nacional de Trujillo"],
    ["name" => "Universidad Nacional Ciro Alegría", "title" => "Universidad Nacional Ciro Alegría"],
    ["name" => "Universidad Autónoma de Ica", "title" => "Universidad Autónoma de Ica"],
    ["name" => "Grupo Educativo Universidad Privada de Ica", "title" => "Grupo Educativo Universidad Privada de Ica"],
    ["name" => "Universidad Nacional San Luis Gonzaga", "title" => "Universidad Nacional San Luis Gonzaga"],
    ["name" => "Universidad Global del Cusco", "title" => "Universidad Global del Cusco"],
    ["name" => "Universidad Privada Líder Peruana", "title" => "Universidad Privada Líder Peruana"],
    ["name" => "Universidad Nacional Intercultural de Quillabamba", "title" => "Universidad Nacional Intercultural de Quillabamba"],
    ["name" => "Universidad Peruana Austral del Cusco", "title" => "Universidad Peruana Austral del Cusco"],
    ["name" => "Universidad Andina del Cusco", "title" => "Universidad Andina del Cusco"],
    ["name" => "Universidad Nacional de San Antonio Abad del Cusco", "title" => "Universidad Nacional de San Antonio Abad del Cusco"],
    ["name" => "Universidad Privada de Pucallpa S.A.C.", "title" => "Universidad Privada de Pucallpa S.A.C."],
    ["name" => "Universidad Nacional Autónoma de Huanta", "title" => "Universidad Nacional Autónoma de Huanta"],
    ["name" => "Universidad de Ayacucho Federico Froebel", "title" => "Universidad de Ayacucho Federico Froebel"],
    ["name" => "Universidad Nacional de San Cristóbal de Huamanga", "title" => "Universidad Nacional de San Cristóbal de Huamanga"],
    ["name" => "Universidad Nacional del Callao", "title" => "Universidad Nacional del Callao"],
    ["name" => "Universidad Marítima del Perú", "title" => "Universidad Marítima del Perú"],
    ["name" => "Universidad Católica San José", "title" => "Universidad Católica San José"],
    ["name" => "Universidad Privada SISE", "title" => "Universidad Privada SISE"],
    ["name" => "Universidad Privada Peruano Alemana S.AC.", "title" => "Universidad Privada Peruano Alemana S.AC."],
    ["name" => "Universidad Santo Domingo de Guzmán", "title" => "Universidad Santo Domingo de Guzmán"],
    ["name" => "Universidad María Auxiliadora", "title" => "Universidad María Auxiliadora"],
    ["name" => "Universidad de Ingeniería y Tecnología", "title" => "Universidad de Ingeniería y Tecnología"],
    ["name" => "Universidad Privada Juan Pablo II", "title" => "Universidad Privada Juan Pablo II"],
    ["name" => "Universidad Interamericana para el Desarrollo", "title" => "Universidad Interamericana para el Desarrollo"],
    ["name" => "Universidad San Andrés", "title" => "Universidad San Andrés"],
    ["name" => "Universidad Peruana de Investigación y Negocios S.A.C.", "title" => "Universidad Peruana de Investigación y Negocios S.A.C."],
    ["name" => "Universidad de Ciencias y Artes de América Latina S.A.C.", "title" => "Universidad de Ciencias y Artes de América Latina S.A.C."],
    ["name" => "Universidad Le Cordon Bleu S.A.C.", "title" => "Universidad Le Cordon Bleu S.A.C."],
    ["name" => "Universidad Peruana de Arte Orval S.A.C.", "title" => "Universidad Peruana de Arte Orval S.A.C."],
    ["name" => "Universidad Peruana Simón Bolivar", "title" => "Universidad Peruana Simón Bolivar"],
    ["name" => "Universidad Privada Arzobispo Loayza S.A.C", "title" => "Universidad Privada Arzobispo Loayza S.A.C"],
    ["name" => "Universidad Jaime Bausate y Meza", "title" => "Universidad Jaime Bausate y Meza"],
    ["name" => "Universidad de Ciencias y Humanidades", "title" => "Universidad de Ciencias y Humanidades"],
    ["name" => "Universidad Autónoma del Perú", "title" => "Universidad Autónoma del Perú"],
    ["name" => "Universidad Sergio Bernales S.A.", "title" => "Universidad Sergio Bernales S.A."],
    ["name" => "Universidad Privada Telesup", "title" => "Universidad Privada Telesup"],
    ["name" => "Universidad Peruana de Ciencias e Informática", "title" => "Universidad Peruana de Ciencias e Informática"],
    ["name" => "Universidad Antonio Ruiz de Montoya", "title" => "Universidad Antonio Ruiz de Montoya"],
    ["name" => "Universidad ESAN", "title" => "Universidad ESAN"],
    ["name" => "Universidad Peruana de las Américas", "title" => "Universidad Peruana de las Américas"],
    ["name" => "Universidad Católica Sedes Sapientiae", "title" => "Universidad Católica Sedes Sapientiae"],
    ["name" => "Universidad Científica del Sur S.A.C.", "title" => "Universidad Científica del Sur S.A.C."],
    ["name" => "Universidad Tecnológica del Perú", "title" => "Universidad Tecnológica del Perú"],
    ["name" => "Universidad Privada San Juan Bautista S.A.C.", "title" => "Universidad Privada San Juan Bautista S.A.C."],
    ["name" => "Universidad Privada Norbert Wiener", "title" => "Universidad Privada Norbert Wiener"],
    ["name" => "Universidad Alas Peruanas", "title" => "Universidad Alas Peruanas"],
    ["name" => "Universidad San Ignacio de Loyola S.A.", "title" => "Universidad San Ignacio de Loyola S.A."],
    ["name" => "Universidad Peruana de Ciencias Aplicadas S.A.C.", "title" => "Universidad Peruana de Ciencias Aplicadas S.A.C."],
    ["name" => "Universidad Marcelino Champagnat", "title" => "Universidad Marcelino Champagnat"],
    ["name" => "Universidad Peruana Unión", "title" => "Universidad Peruana Unión"],
    ["name" => "Universidad Ricardo Palma", "title" => "Universidad Ricardo Palma"],
    ["name" => "Universidad Inca Garcilaso de la Vega", "title" => "Universidad Inca Garcilaso de la Vega"],
    ["name" => "Universidad Femenina del Sagrado Corazón", "title" => "Universidad Femenina del Sagrado Corazón"],
    ["name" => "Universidad de San Martín de Porres", "title" => "Universidad de San Martín de Porres"],
    ["name" => "Universidad de Lima", "title" => "Universidad de Lima"],
    ["name" => "Universidad del Pacífico", "title" => "Universidad del Pacífico"],
    ["name" => "Universidad Peruana Cayetano Heredia", "title" => "Universidad Peruana Cayetano Heredia"],
    ["name" => "Pontificia Universidad Católica del Perú", "title" => "Pontificia Universidad Católica del Perú"],
    ["name" => "Escuela De Posgrado-Gerens S.A.C.", "title" => "Escuela De Posgrado-Gerens S.A.C."],
    ["name" => "Universidad Nacional de Educación Enrique Guzmán y Valle", "title" => "Universidad Nacional de Educación Enrique Guzmán y Valle"],
    ["name" => "Facultad de Teología Pontificia y Civil de Lima", "title" => "Facultad de Teología Pontificia y Civil de Lima"],
    ["name" => "Universidad Nacional de Cañete", "title" => "Universidad Nacional de Cañete"],
    ["name" => "Universidad Nacional de Barranca", "title" => "Universidad Nacional de Barranca"],
    ["name" => "Universidad Nacional José Faustino Sánchez Carrión", "title" => "Universidad Nacional José Faustino Sánchez Carrión"],
    ["name" => "Universidad Nacional Tecnológica de Lima Sur", "title" => "Universidad Nacional Tecnológica de Lima Sur"],
    ["name" => "Universidad Nacional Federico Villarreal", "title" => "Universidad Nacional Federico Villarreal"],
    ["name" => "Universidad Nacional Agraria La Molina", "title" => "Universidad Nacional Agraria La Molina"],
    ["name" => "Universidad Nacional de Ingeniería", "title" => "Universidad Nacional de Ingeniería"],
    ["name" => "Universidad Nacional Mayor de San Marcos", "title" => "Universidad Nacional Mayor de San Marcos"],
    ["name" => "Adex", "title" => "Adex"],
];

$GLOBALS['institution_list'] = $institution_list;